//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalServiceWeb.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_TechnicalServiceEntities1 : DbContext
    {
        public Db_TechnicalServiceEntities1()
            : base("name=Db_TechnicalServiceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblDefectiveProduct> TblDefectiveProducts { get; set; }
        public virtual DbSet<TblProcess> TblProcesses { get; set; }
        public virtual DbSet<TblProduct> TblProducts { get; set; }
        public virtual DbSet<TblCathegory> TblCathegories { get; set; }
        public virtual DbSet<TBl_Contact> TBl_Contact { get; set; }
        public virtual DbSet<TblAbout> TblAbouts { get; set; }
    }
}
