//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalServiceWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBl_Contact
    {
        public int ContactId { get; set; }
        public string ContactNameSurname { get; set; }
        public string ContactEMail { get; set; }
        public string ContactContext { get; set; }
    }
}
