//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalServiceWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDefectiveProduct
    {
        public int FaultId { get; set; }
        public Nullable<int> FaultProcess { get; set; }
        public string FaultProblem { get; set; }
        public string FaultNote { get; set; }
        public Nullable<decimal> FaultEstimatedPrice { get; set; }
        public string FaultTransactionsMade { get; set; }
        public Nullable<decimal> FaultNetPrice { get; set; }
        public string FaultSerieNo { get; set; }
    
        public virtual TblProcess TblProcess { get; set; }
    }
}
