//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalServiceWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProcess()
        {
            this.TblDefectiveProducts = new HashSet<TblDefectiveProduct>();
        }
    
        public int ProcessId { get; set; }
        public string ProcessTitle { get; set; }
        public string ProcessDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDefectiveProduct> TblDefectiveProducts { get; set; }
    }
}
