//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndTechnicalServiceWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProduct
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductBrand { get; set; }
        public Nullable<decimal> ProductBuyingPrice { get; set; }
        public Nullable<decimal> ProductSellingPrice { get; set; }
        public Nullable<short> ProductStock { get; set; }
        public Nullable<int> ProductCathegory { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<bool> ProductStatus { get; set; }
    
        public virtual TblCathegory TblCathegory { get; set; }
    }
}
